/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MalteHedenstrom (https://sketchfab.com/MalteHedenstrom)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/space-helmet-study-367cec9498314678b0ab6cc93bbb82f6
Title: Space Helmet Study
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/astronaut.glb')

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });

  return (
    <group {...props} dispose={null}
    ref = {modelRef}
    scale={[7, 7, 7]}
    rotation={[0.6, -1, 0]}
    position={[0, 0.7, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder19_UV_Material_0.geometry}
        material={materials.UV_Material}
        position={[0.131, 0.145, 0.103]}
        rotation={[2.056, 0.387, -0.893]}
        scale={0.066}
      />
    </group>
  )
}

useGLTF.preload('/models/astronaut.glb')
