/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Microsoft (https://sketchfab.com/microsoft)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-shuttle-ff4b00b7ebb24fdd98fb96b08f2c43c9
Title: Space Shuttle
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/shutle.glb')

  const modelRef = useRef();
  useFrame(() => {
    modelRef.current.rotation.z += 0.007;
  });


  return (
    <group {...props} dispose={null}
    scale={[0.2, 0.2, 0.2]}
    rotation={[-1,0,0]}
    position={[0, 0, 0]}
    ref={modelRef}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Material__197}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.288}
      />
    </group>
  )
}

useGLTF.preload('/models/shutle.glb')