/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: drei.lu (https://sketchfab.com/drei.lu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-exploration-wlp-series-8-91964c1ce1a34c3985b6257441efa500
Title: Space exploration [WLP series #8]
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Space(props) {
  const { nodes, materials } = useGLTF('/models/space.glb')

  const modelRef = useRef()

  useFrame((state, delta, xrFrame) => {
    modelRef.current.rotation.y += -0.002;
    modelRef.current.position.y = 0.8 + Math.sin(state.clock.elapsedTime) * 0.15;
  })

  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[0, 0.8, 0]}
    scale={[0.17, 0.17, 0.17]}
    rotation={([0.3,0,0])}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planet001.geometry}
        material={materials.scene}
        position={[-0.003, -6.331, -0.024]}
        rotation={[-1.333, -0.545, 0.562]}
        scale={7}
      />
    </group>
  )
}

useGLTF.preload('/models/space.glb')